quarkus:
  http:
    port: 8801
  hibernate-orm:
    sql-load-script: import.sql
    log:
      sql: true
    database:
      generation: drop-and-create
  datasource:
    reactive:
      url: vertx-reactive:mysql://localhost:3306/panache_db
    db-kind: mysql
    username: root
    password: 123456
#    jdbc:
#      url: jdbc:mysql://localhost:3306/panache_db
